### ISSUE TITLE
Make all the Models

### ISSUE THREAD

**Issue by athul** [agrivator/agrivator-backend#3]
![WhatsApp Image 2020-03-19 at 9 58 06 PM](https://user-images.githubusercontent.com/40897573/77725902-ae118380-701c-11ea-9b2c-f90faede2c05.jpeg)
You can use this for reference.
Basically the completed models are
- [x] Admin Model
- [x] Super User Model

**Comment by thetronjohnson** [comment]
Shop and Home Delivery vere apps akkam

**Comment by athul** [comment]
Okay .

What about farmer? or is farmer the user?

**Comment by thetronjohnson** [comment]
Yeah.. Farmer/Enduser/Staff ellam users il idam

**Comment by thetronjohnson** [comment]
Oru product model venam and it only applies if the user is a farmer

**Comment by athul** [comment]
Hey @thetronjohnson  and @ann-philip  Any Updates?

**Comment by ann-philip** [comment]
will start working on it.

**Comment by athul** [comment]
@thetronjohnson please lead her the right way

**Comment by thetronjohnson** [comment]
I'll take care of the user app, I'm modifying the user creation stuff
@ann-philip Can you create an app for the shop and and create the following fields in the shops model

- Name
- Location( put TextFieldForNow)
- Qty They can store
- Contact Number

**Comment by thetronjohnson** [comment]
@athul Eda thinking about it nammak Shops and Homedelivery ne users ayit imagine chyan patille

**Comment by thetronjohnson** [comment]
@athul As extensions of the main user Class

**Comment by thetronjohnson** [comment]
@athul atayath like Farmer,Shop and Home being inherited classes of the CustomUser we created

**Comment by athul** [comment]
All model stuff is for you to handle. Yes, that seems a good idea, mentioning @abhinavprasad791 too for feed back

**Comment by thetronjohnson** [comment]
Products enna model is shared by all three so complicated akkkandallo.

**Comment by thetronjohnson** [comment]
@ann-philip Can you inherit the custom Usermodel "User" and create three new models for Farmer, Shops and Home Delivery with the basic Fields

**Comment by athul** [comment]
@thetronjohnson and @ann-philip I have to set a deadline since we procrastinated a bit. We need to complete the models by Tuesday(07/04/20) max. Please cooperate with me on this. 🥺

**Comment by ann-philip** [comment]
Clarification on shop and home delivery?can we set a call tomorrow

**Comment by athul** [comment]
sure
